; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Spolszczenie do Legacy of Kain™ Soul Reaver 1&2"
#define MyAppVersion "1.3.2"
#define MyAppPublisher "Nosgothica Polonization Group"
#define MyAppURL "https://github.com/Nidrax/sr-remaster-pl"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{DE08E967-16FA-485F-96C4-B1CAB6CEACBB}
AppName=Spolszczenie do Legacy of Kain™ Soul Reaver 1&2
AppVersion=1.3.2
DefaultDirName={code:GetInstallationPath}
LicenseFile=../LICENSE
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=output
OutputBaseFilename=sr-remaster-pl-1.3.2
SetupIconFile=srp.ico
SolidCompression=yes
WizardStyle=modern
WizardImageFile=wizardimg.bmp
WizardSmallImageFile=wizardsmall.bmp
Uninstallable=no

[Code]
var
  InstallationPath: string;

function GetInstallationPath(Param: string): string;
begin
  // Detected path is cached, as this gets called multiple times
  if InstallationPath = '' then
  begin
    if RegQueryStringValue(
         HKLM64,
         'SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Steam App 2521380',
         'InstallLocation', InstallationPath) then
    begin
      Log('Detected Steam installation: ' + InstallationPath);
    end
      else
    if RegQueryStringValue(
         HKLM32, 'SOFTWARE\GOG.com\Games\1214553287',
         'path', InstallationPath) then
    begin
      Log('Detected GOG installation: ' + InstallationPath);
    end
      else
    begin
      InstallationPath := 'C:\Program Files (x86)\Spolszczenie Soul Reaver I-II';
      Log('No installation detected, using the default path: ' +
            InstallationPath);
    end;
  end;
  Result := InstallationPath;
end;

[Languages]
Name: "polish"; MessagesFile: "compiler:Languages\Polish.isl"
Name: "english"; MessagesFile: "compiler:Languages\Polish.isl"

[Files]
Source: "..\1\TEXT\PL\*"; DestDir: "{app}\1\TEXT\RU"; Flags: ignoreversion
Source: "..\2\TEXT\PL\*"; DestDir: "{app}\2\TEXT\RU"; Flags: ignoreversion
Source: "..\1\TEX\*"; DestDir: "{app}\1\TEX"; Flags: ignoreversion
Source: "..\2\TEX\*"; DestDir: "{app}\2\TEX"; Flags: ignoreversion
Source: "..\1\PIX\TBC_PL_HD.dds"; DestDir: "{app}\1\PIX"; DestName: "TBC_RU_HD.DDS"; Flags: ignoreversion
Source: "..\1\PIX\VERSE_PL_HD.dds"; DestDir: "{app}\1\PIX"; DestName: "VERSE_RU_HD.DDS"; Flags: ignoreversion
Source: "..\2\PIX\THEEND_PL_HD.dds"; DestDir: "{app}\1\PIX"; DestName: "THEEND_RU_HD.DDS"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

